### ISSUE TITLE
Exception running `kld.py`

### ISSUE THREAD

**Issue by cogumbreiro** [capergroup/salento#4]
Hi, @vijay-murali,

I am trying to debug the error below and for that I was looking at the implementation of `kld.py`.

## Error

```python
tarted at 2017-11-27 16:42:05.398390
2017-11-27 16:42:05.398588: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
### foo.c
Traceback (most recent call last):
  File "../salento/statistical/kld.py", line 150, in <module>
    main()
  File "../salento/statistical/kld.py", line 65, in main
    klds = [(l, kld.compute(l, pack)) for l in locations]
  File "../salento/statistical/kld.py", line 65, in <listcomp>
    klds = [(l, kld.compute(l, pack)) for l in locations]
  File "../salento/statistical/kld.py", line 131, in compute
    samples = [sample(seqs_l, nsamples=1) for i in range(self.args.num_iters)]
  File "../salento/statistical/kld.py", line 131, in <listcomp>
    samples = [sample(seqs_l, nsamples=1) for i in range(self.args.num_iters)]
  File "/home/tiago/Work/salento/statistical/utils.py", line 20, in sample
    samples = [random.choice(s) for i in range(nsamples)] if nsamples > 1 else random.choice(s)
  File "/usr/lib/python3.6/random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```
## Input
```json
{"packages": [
    {"data": [
        {"sequence": [
            {
              "call": "pthread_mutex_lock",
              "states": [],
              "location": "foo.c:2"
            },
            {
              "call": "pthread_mutex_unlock",
              "states": [],
              "location": "foo.c:1"
            }
         ]}
    ],
    "name": "foo.c"
    }
]}
```

## Walk through

In function `main()` we find the following code:
```python
        for pack in parser.packages:
            locations = parser.locations(pack)
            # ...
            klds = [(l, kld.compute(l, pack)) for l in locations]
```

For this input we get that there is only one package, where `locations = ['foo.c:1', 'foo.c:2']`.

Then we have a call to `compute(self, l, pack)`, where in the first line we can find:
```python
        seqs_l = self.parser.sequences(pack, l)
```
According to the documentation of `sequences`:
> If location is given, then get all sequences in package that end at location.`

Hence, for `foo.c:1` we get the only sequence in the input and for `foo.c:2` we get `seqs_l = []` which then triggers the error.

**Comment by cogumbreiro** [comment]
Closing as the code was rewritten.
