### ISSUE TITLE
Salento can't handle unknown vocabs

### ISSUE THREAD

**Issue by cogumbreiro** [capergroup/salento#7]
The problem appears to be that Salento's internals are not expecting unknown vocabs. I am wondering if we should just filter out unknown vocabs when ranging through, say `Aggregator.events`.

@vijay-murali, thoughts?

I'm getting this error when running the sequence aggregator:
```
Package 1----
Traceback (most recent call last):
  File "/home/tgc/salento/src/main/python/salento/aggregators/sequence_aggregator.py", line 52, in <module>
    aggregator.run()
  File "/home/tgc/salento/src/main/python/salento/aggregators/sequence_aggregator.py", line 38, in run
    llh += math.log(self.distribution_next_call(spec, events[:i], call=self.call(event)))
  File "/home/tgc/salento/src/main/python/salento/aggregators/base.py", line 73, in distribution_next_call
    return dist if call is None else dist[call]
KeyError: 'cogl_pipeline_set_layer_filters'
```

**Comment by cogumbreiro** [comment]
Same error shows up when using klb.
```
Traceback (most recent call last):
  File "/home/tgc/salento/src/main/python/salento/aggregators/kld_aggregator.py", line 92, in <module>
    aggregator.run()
  File "/home/tgc/salento/src/main/python/salento/aggregators/kld_aggregator.py", line 79, in run
    kld_score = self.compute_kld(spec, seqs_l)
  File "/home/tgc/salento/src/main/python/salento/aggregators/kld_aggregator.py", line 59, in compute_kld
    log_q = self.log_likelihood(spec, sequence)
  File "/home/tgc/salento/src/main/python/salento/aggregators/kld_aggregator.py", line 41, in log_likelihood
    llh += math.log(self.distribution_next_call(spec, events[:i], call=call))
  File "/home/tgc/salento/src/main/python/salento/aggregators/base.py", line 73, in distribution_next_call
    return dist if call is None else dist[call]
KeyError: 'cogl_pipeline_set_layer_filters'
```

**Comment by vijay-murali** [comment]
Yeah, the model is not implemented to work with unknown vocabs. You can filter them out in a pre-processing step.

**Comment by cogumbreiro** [comment]
This was handled in PR #8.
