### ISSUE TITLE
Salento crashing with `states` defined

### ISSUE THREAD

**Issue by cogumbreiro** [capergroup/salento#9]
```
Traceback (most recent call last):
  File "/home/tgc/salento/src/main/python/salento/aggregators/kld_aggregator.py", line 94, in <module>
    aggregator.run()
  File "/home/tgc/salento/src/main/python/salento/aggregators/kld_aggregator.py", line 81, in run
    kld_score = self.compute_kld(spec, seqs_l)
  File "/home/tgc/salento/src/main/python/salento/aggregators/kld_aggregator.py", line 59, in compute_kld
    log_q = self.log_likelihood(spec, sequence)
  File "/home/tgc/salento/src/main/python/salento/aggregators/kld_aggregator.py", line 44, in log_likelihood
    llh += math.log(self.distribution_next_state(spec, events[:i] + [partial_event], state=state))
  File "/home/tgc/salento/src/main/python/salento/aggregators/base.py", line 91, in distribution_next_state
    return dist[state]
KeyError: '4#5'
```

**Comment by cogumbreiro** [comment]
This bug appears to be specific to the kld aggregator. It is not triggered by sequences aggregator.
